/**
 * Now it is enough to specify one of the env var as the default endpoint:
    CONSTRUCTOR_DETECTOR_ENDPOINT
    ENDPOINT
    CONSTRUCTOR
    CONSTRUCTOR_ENDPOINT
    WEB3_ENDPOINT
    ETHEREUM_CONSTRUCTOR_DETECTOR_ENDPOINT
    BSC_CONSTRUCTOR_DETECTOR_ENDPOINT
    BINANCE_CONSTRUCTOR_DETECTOR_ENDPOINT
    POLYGON_CONSTRUCTOR_DETECTOR_ENDPOINT
    ARBITRUM_CONSTRUCTOR_DETECTOR_ENDPOINT
    HECO_CONSTRUCTOR_DETECTOR_ENDPOINT
    ETH_CONSTRUCTOR_DETECTOR_ENDPOINT
    ETHER_CONSTRUCTOR_DETECTOR_ENDPOINT
    ETHEREUM_ENDPOINT
    BSC_ENDPOINT
    BINANCE_ENDPOINT
    POLYGON_ENDPOINT
    ARBITRUM_ENDPOINT
    HECO_ENDPOINT
    ETH_ENDPOINT
    ETHER_ENDPOINT
    ETHEREUM_CONSTRUCTOR
    BSC_CONSTRUCTOR
    BINANCE_CONSTRUCTOR
    POLYGON_CONSTRUCTOR
    ARBITRUM_CONSTRUCTOR
    HECO_CONSTRUCTOR
    ETH_CONSTRUCTOR
    ETHER_CONSTRUCTOR
    ETHEREUM_CONSTRUCTOR_ENDPOINT
    BSC_CONSTRUCTOR_ENDPOINT
    BINANCE_CONSTRUCTOR_ENDPOINT
    POLYGON_CONSTRUCTOR_ENDPOINT
    ARBITRUM_CONSTRUCTOR_ENDPOINT
    HECO_CONSTRUCTOR_ENDPOINT
    ETH_CONSTRUCTOR_ENDPOINT
    ETHER_CONSTRUCTOR_ENDPOINT
    ETHEREUM_WEB3_ENDPOINT
    BSC_WEB3_ENDPOINT
    BINANCE_WEB3_ENDPOINT
    POLYGON_WEB3_ENDPOINT
    ARBITRUM_WEB3_ENDPOINT
    HECO_WEB3_ENDPOINT
    ETH_WEB3_ENDPOINT
    ETHER_WEB3_ENDPOINT
    CONSTRUCTOR_DETECTOR_ENDPOINT_ETHEREUM
    CONSTRUCTOR_DETECTOR_ENDPOINT_BSC
    CONSTRUCTOR_DETECTOR_ENDPOINT_BINANCE
    CONSTRUCTOR_DETECTOR_ENDPOINT_POLYGON
    CONSTRUCTOR_DETECTOR_ENDPOINT_ARBITRUM
    CONSTRUCTOR_DETECTOR_ENDPOINT_HECO
    CONSTRUCTOR_DETECTOR_ENDPOINT_ETH
    CONSTRUCTOR_DETECTOR_ENDPOINT_ETHER
    ENDPOINT_ETHEREUM
    ENDPOINT_BSC
    ENDPOINT_BINANCE
    ENDPOINT_POLYGON
    ENDPOINT_ARBITRUM
    ENDPOINT_HECO
    ENDPOINT_ETH
    ENDPOINT_ETHER
    CONSTRUCTOR_ETHEREUM
    CONSTRUCTOR_BSC
    CONSTRUCTOR_BINANCE
    CONSTRUCTOR_POLYGON
    CONSTRUCTOR_ARBITRUM
    CONSTRUCTOR_HECO
    CONSTRUCTOR_ETH
    CONSTRUCTOR_ETHER
    CONSTRUCTOR_ENDPOINT_ETHEREUM
    CONSTRUCTOR_ENDPOINT_BSC
    CONSTRUCTOR_ENDPOINT_BINANCE
    CONSTRUCTOR_ENDPOINT_POLYGON
    CONSTRUCTOR_ENDPOINT_ARBITRUM
    CONSTRUCTOR_ENDPOINT_HECO
    CONSTRUCTOR_ENDPOINT_ETH
    CONSTRUCTOR_ENDPOINT_ETHER
    WEB3_ENDPOINT_ETHEREUM
    WEB3_ENDPOINT_BSC
    WEB3_ENDPOINT_BINANCE
    WEB3_ENDPOINT_POLYGON
    WEB3_ENDPOINT_ARBITRUM
    WEB3_ENDPOINT_HECO
    WEB3_ENDPOINT_ETH
    WEB3_ENDPOINT_ETHER
    URL_CONSTRUCTOR_DETECTOR_ENDPOINT
    CONSTRUCTOR_DETECTOR_ENDPOINT_URL
    URL_ENDPOINT
    ENDPOINT_URL
    URL_CONSTRUCTOR
    CONSTRUCTOR_URL
    URL_CONSTRUCTOR_ENDPOINT
    CONSTRUCTOR_ENDPOINT_URL
    URL_WEB3_ENDPOINT
    WEB3_ENDPOINT_URL
    URL_ETHEREUM_CONSTRUCTOR_DETECTOR_ENDPOINT
    ETHEREUM_CONSTRUCTOR_DETECTOR_ENDPOINT_URL
    URL_BSC_CONSTRUCTOR_DETECTOR_ENDPOINT
    BSC_CONSTRUCTOR_DETECTOR_ENDPOINT_URL
    URL_BINANCE_CONSTRUCTOR_DETECTOR_ENDPOINT
    BINANCE_CONSTRUCTOR_DETECTOR_ENDPOINT_URL
    URL_POLYGON_CONSTRUCTOR_DETECTOR_ENDPOINT
    POLYGON_CONSTRUCTOR_DETECTOR_ENDPOINT_URL
    URL_ARBITRUM_CONSTRUCTOR_DETECTOR_ENDPOINT
    ARBITRUM_CONSTRUCTOR_DETECTOR_ENDPOINT_URL
    URL_HECO_CONSTRUCTOR_DETECTOR_ENDPOINT
    HECO_CONSTRUCTOR_DETECTOR_ENDPOINT_URL
    URL_ETH_CONSTRUCTOR_DETECTOR_ENDPOINT
    ETH_CONSTRUCTOR_DETECTOR_ENDPOINT_URL
    URL_ETHER_CONSTRUCTOR_DETECTOR_ENDPOINT
    ETHER_CONSTRUCTOR_DETECTOR_ENDPOINT_URL
    URL_ETHEREUM_ENDPOINT
    ETHEREUM_ENDPOINT_URL
    URL_BSC_ENDPOINT
    BSC_ENDPOINT_URL
    URL_BINANCE_ENDPOINT
    BINANCE_ENDPOINT_URL
    URL_POLYGON_ENDPOINT
    POLYGON_ENDPOINT_URL
    URL_ARBITRUM_ENDPOINT
    ARBITRUM_ENDPOINT_URL
    URL_HECO_ENDPOINT
    HECO_ENDPOINT_URL
    URL_ETH_ENDPOINT
    ETH_ENDPOINT_URL
    URL_ETHER_ENDPOINT
    ETHER_ENDPOINT_URL
    URL_ETHEREUM_CONSTRUCTOR
    ETHEREUM_CONSTRUCTOR_URL
    URL_BSC_CONSTRUCTOR
    BSC_CONSTRUCTOR_URL
    URL_BINANCE_CONSTRUCTOR
    BINANCE_CONSTRUCTOR_URL
    URL_POLYGON_CONSTRUCTOR
    POLYGON_CONSTRUCTOR_URL
    URL_ARBITRUM_CONSTRUCTOR
    ARBITRUM_CONSTRUCTOR_URL
    URL_HECO_CONSTRUCTOR
    HECO_CONSTRUCTOR_URL
    URL_ETH_CONSTRUCTOR
    ETH_CONSTRUCTOR_URL
    URL_ETHER_CONSTRUCTOR
    ETHER_CONSTRUCTOR_URL
    URL_ETHEREUM_CONSTRUCTOR_ENDPOINT
    ETHEREUM_CONSTRUCTOR_ENDPOINT_URL
    URL_BSC_CONSTRUCTOR_ENDPOINT
    BSC_CONSTRUCTOR_ENDPOINT_URL
    URL_BINANCE_CONSTRUCTOR_ENDPOINT
    BINANCE_CONSTRUCTOR_ENDPOINT_URL
    URL_POLYGON_CONSTRUCTOR_ENDPOINT
    POLYGON_CONSTRUCTOR_ENDPOINT_URL
    URL_ARBITRUM_CONSTRUCTOR_ENDPOINT
    ARBITRUM_CONSTRUCTOR_ENDPOINT_URL
    URL_HECO_CONSTRUCTOR_ENDPOINT
    HECO_CONSTRUCTOR_ENDPOINT_URL
    URL_ETH_CONSTRUCTOR_ENDPOINT
    ETH_CONSTRUCTOR_ENDPOINT_URL
    URL_ETHER_CONSTRUCTOR_ENDPOINT
    ETHER_CONSTRUCTOR_ENDPOINT_URL
    URL_ETHEREUM_WEB3_ENDPOINT
    ETHEREUM_WEB3_ENDPOINT_URL
    URL_BSC_WEB3_ENDPOINT
    BSC_WEB3_ENDPOINT_URL
    URL_BINANCE_WEB3_ENDPOINT
    BINANCE_WEB3_ENDPOINT_URL
    URL_POLYGON_WEB3_ENDPOINT
    POLYGON_WEB3_ENDPOINT_URL
    URL_ARBITRUM_WEB3_ENDPOINT
    ARBITRUM_WEB3_ENDPOINT_URL
    URL_HECO_WEB3_ENDPOINT
    HECO_WEB3_ENDPOINT_URL
    URL_ETH_WEB3_ENDPOINT
    ETH_WEB3_ENDPOINT_URL
    URL_ETHER_WEB3_ENDPOINT
    ETHER_WEB3_ENDPOINT_URL
    URL_CONSTRUCTOR_DETECTOR_ENDPOINT_ETHEREUM
    CONSTRUCTOR_DETECTOR_ENDPOINT_ETHEREUM_URL
    URL_CONSTRUCTOR_DETECTOR_ENDPOINT_BSC
    CONSTRUCTOR_DETECTOR_ENDPOINT_BSC_URL
    URL_CONSTRUCTOR_DETECTOR_ENDPOINT_BINANCE
    CONSTRUCTOR_DETECTOR_ENDPOINT_BINANCE_URL
    URL_CONSTRUCTOR_DETECTOR_ENDPOINT_POLYGON
    CONSTRUCTOR_DETECTOR_ENDPOINT_POLYGON_URL
    URL_CONSTRUCTOR_DETECTOR_ENDPOINT_ARBITRUM
    CONSTRUCTOR_DETECTOR_ENDPOINT_ARBITRUM_URL
    URL_CONSTRUCTOR_DETECTOR_ENDPOINT_HECO
    CONSTRUCTOR_DETECTOR_ENDPOINT_HECO_URL
    URL_CONSTRUCTOR_DETECTOR_ENDPOINT_ETH
    CONSTRUCTOR_DETECTOR_ENDPOINT_ETH_URL
    URL_CONSTRUCTOR_DETECTOR_ENDPOINT_ETHER
    CONSTRUCTOR_DETECTOR_ENDPOINT_ETHER_URL
    URL_ENDPOINT_ETHEREUM
    ENDPOINT_ETHEREUM_URL
    URL_ENDPOINT_BSC
    ENDPOINT_BSC_URL
    URL_ENDPOINT_BINANCE
    ENDPOINT_BINANCE_URL
    URL_ENDPOINT_POLYGON
    ENDPOINT_POLYGON_URL
    URL_ENDPOINT_ARBITRUM
    ENDPOINT_ARBITRUM_URL
    URL_ENDPOINT_HECO
    ENDPOINT_HECO_URL
    URL_ENDPOINT_ETH
    ENDPOINT_ETH_URL
    URL_ENDPOINT_ETHER
    ENDPOINT_ETHER_URL
    URL_CONSTRUCTOR_ETHEREUM
    CONSTRUCTOR_ETHEREUM_URL
    URL_CONSTRUCTOR_BSC
    CONSTRUCTOR_BSC_URL
    URL_CONSTRUCTOR_BINANCE
    CONSTRUCTOR_BINANCE_URL
    URL_CONSTRUCTOR_POLYGON
    CONSTRUCTOR_POLYGON_URL
    URL_CONSTRUCTOR_ARBITRUM
    CONSTRUCTOR_ARBITRUM_URL
    URL_CONSTRUCTOR_HECO
    CONSTRUCTOR_HECO_URL
    URL_CONSTRUCTOR_ETH
    CONSTRUCTOR_ETH_URL
    URL_CONSTRUCTOR_ETHER
    CONSTRUCTOR_ETHER_URL
    URL_CONSTRUCTOR_ENDPOINT_ETHEREUM
    CONSTRUCTOR_ENDPOINT_ETHEREUM_URL
    URL_CONSTRUCTOR_ENDPOINT_BSC
    CONSTRUCTOR_ENDPOINT_BSC_URL
    URL_CONSTRUCTOR_ENDPOINT_BINANCE
    CONSTRUCTOR_ENDPOINT_BINANCE_URL
    URL_CONSTRUCTOR_ENDPOINT_POLYGON
    CONSTRUCTOR_ENDPOINT_POLYGON_URL
    URL_CONSTRUCTOR_ENDPOINT_ARBITRUM
    CONSTRUCTOR_ENDPOINT_ARBITRUM_URL
    URL_CONSTRUCTOR_ENDPOINT_HECO
    CONSTRUCTOR_ENDPOINT_HECO_URL
    URL_CONSTRUCTOR_ENDPOINT_ETH
    CONSTRUCTOR_ENDPOINT_ETH_URL
    URL_CONSTRUCTOR_ENDPOINT_ETHER
    CONSTRUCTOR_ENDPOINT_ETHER_URL
    URL_WEB3_ENDPOINT_ETHEREUM
    WEB3_ENDPOINT_ETHEREUM_URL
    URL_WEB3_ENDPOINT_BSC
    WEB3_ENDPOINT_BSC_URL
    URL_WEB3_ENDPOINT_BINANCE
    WEB3_ENDPOINT_BINANCE_URL
    URL_WEB3_ENDPOINT_POLYGON
    WEB3_ENDPOINT_POLYGON_URL
    URL_WEB3_ENDPOINT_ARBITRUM
    WEB3_ENDPOINT_ARBITRUM_URL
    URL_WEB3_ENDPOINT_HECO
    WEB3_ENDPOINT_HECO_URL
    URL_WEB3_ENDPOINT_ETH
    WEB3_ENDPOINT_ETH_URL
    URL_WEB3_ENDPOINT_ETHER
    WEB3_ENDPOINT_ETHER_URL
*/

require("dotenv").config();

const base = [
    'CONSTRUCTOR_DETECTOR_ENDPOINT',
    'ENDPOINT',
    'CONSTRUCTOR',
    'CONSTRUCTOR_ENDPOINT',
    'WEB3_ENDPOINT',
];

const keysUrl = (keys: string[]) => {
    let res: string[] = [];

    keys.map(key => {
        res.push(`URL_${key}`)
        res.push(`${key}_URL`)
    })

    return [...keys, ...res];
}

const keysNetworks = (keys: string[], networks: string[]) => {
    let res: string[] = [];

    keys.map(key => {
        networks.map(network => {
            res.push(`${network}_${key}`)
        })
    })

    keys.map(key => {
        networks.map(network => {
            res.push(`${key}_${network}`)
        })
    })

    return [...keys, ...res];
}

const networks = [
    "ETHEREUM",
    "BSC",
    "BINANCE",
    "POLYGON",
    "ARBITRUM",
    "HECO",
    "ETH",
    "ETHER"
]
const keys = keysUrl(keysNetworks(base, networks))

const findEndpoint = (keys: string[]) => {
    for (let i = 0; i < keys.length; i++) {
        const key = keys[i];
        if(process.env[key] !== undefined) {
            return process.env[key];
        }
        
    }
    return undefined;
}

const defaultEndpoint = findEndpoint(keys);
export default defaultEndpoint;
